---
- name: ensure that gitlabot repository is present
  git:
    repo: 'https://github.com/SaphireVert/ict-bot'
    dest: /srv/ict-bot
    version: "deployment"
    force: yes

- name: Copy secrets from keybase
  copy:
    src: /keybase/team/epfl_idevfsd.apprentis.common/apprentis_projects/ict-bot/secret.json
    dest: /srv/ict-bot/dev/secret.json
